export default [
  {
  "login": "muhammai2000",
  "id": 52387878,
  "node_id": "MDQ6VXNlcjUyMzg3ODc4",
  "avatar_url": "https://avatars.githubusercontent.com/u/52387878?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/muhammai2000",
  "html_url": "https://github.com/muhammai2000",
  "followers_url": "https://api.github.com/users/muhammai2000/followers",
  "following_url": "https://api.github.com/users/muhammai2000/following{/other_user}",
  "gists_url": "https://api.github.com/users/muhammai2000/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/muhammai2000/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/muhammai2000/subscriptions",
  "organizations_url": "https://api.github.com/users/muhammai2000/orgs",
  "repos_url": "https://api.github.com/users/muhammai2000/repos",
  "events_url": "https://api.github.com/users/muhammai2000/events{/privacy}",
  "received_events_url": "https://api.github.com/users/muhammai2000/received_events",
  "type": "User",
  "site_admin": false
  },
  {
  "login": "aribow627",
  "id": 57337167,
  "node_id": "MDQ6VXNlcjU3MzM3MTY3",
  "avatar_url": "https://avatars.githubusercontent.com/u/57337167?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/aribow627",
  "html_url": "https://github.com/aribow627",
  "followers_url": "https://api.github.com/users/aribow627/followers",
  "following_url": "https://api.github.com/users/aribow627/following{/other_user}",
  "gists_url": "https://api.github.com/users/aribow627/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/aribow627/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/aribow627/subscriptions",
  "organizations_url": "https://api.github.com/users/aribow627/orgs",
  "repos_url": "https://api.github.com/users/aribow627/repos",
  "events_url": "https://api.github.com/users/aribow627/events{/privacy}",
  "received_events_url": "https://api.github.com/users/aribow627/received_events",
  "type": "User",
  "site_admin": false
  },
  {
  "login": "melanietr98",
  "id": 102996216,
  "node_id": "U_kgDOBiOY-A",
  "avatar_url": "https://avatars.githubusercontent.com/u/102996216?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/melanietr98",
  "html_url": "https://github.com/melanietr98",
  "followers_url": "https://api.github.com/users/melanietr98/followers",
  "following_url": "https://api.github.com/users/melanietr98/following{/other_user}",
  "gists_url": "https://api.github.com/users/melanietr98/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/melanietr98/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/melanietr98/subscriptions",
  "organizations_url": "https://api.github.com/users/melanietr98/orgs",
  "repos_url": "https://api.github.com/users/melanietr98/repos",
  "events_url": "https://api.github.com/users/melanietr98/events{/privacy}",
  "received_events_url": "https://api.github.com/users/melanietr98/received_events",
  "type": "User",
  "site_admin": false
  },
  {
  "login": "Anabel-Santillan",
  "id": 102996606,
  "node_id": "U_kgDOBiOafg",
  "avatar_url": "https://avatars.githubusercontent.com/u/102996606?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/Anabel-Santillan",
  "html_url": "https://github.com/Anabel-Santillan",
  "followers_url": "https://api.github.com/users/Anabel-Santillan/followers",
  "following_url": "https://api.github.com/users/Anabel-Santillan/following{/other_user}",
  "gists_url": "https://api.github.com/users/Anabel-Santillan/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/Anabel-Santillan/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/Anabel-Santillan/subscriptions",
  "organizations_url": "https://api.github.com/users/Anabel-Santillan/orgs",
  "repos_url": "https://api.github.com/users/Anabel-Santillan/repos",
  "events_url": "https://api.github.com/users/Anabel-Santillan/events{/privacy}",
  "received_events_url": "https://api.github.com/users/Anabel-Santillan/received_events",
  "type": "User",
  "site_admin": false
  }
  ];
