export default {
  "login": "YaredBachaGari",
"id": 24825276,
"node_id": "MDQ6VXNlcjI0ODI1Mjc2",
"avatar_url": "https://avatars.githubusercontent.com/u/24825276?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/YaredBachaGari",
"html_url": "https://github.com/YaredBachaGari",
"followers_url": "https://api.github.com/users/YaredBachaGari/followers",
"following_url": "https://api.github.com/users/YaredBachaGari/following{/other_user}",
"gists_url": "https://api.github.com/users/YaredBachaGari/gists{/gist_id}",
"starred_url": "https://api.github.com/users/YaredBachaGari/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/YaredBachaGari/subscriptions",
"organizations_url": "https://api.github.com/users/YaredBachaGari/orgs",
"repos_url": "https://api.github.com/users/YaredBachaGari/repos",
"events_url": "https://api.github.com/users/YaredBachaGari/events{/privacy}",
"received_events_url": "https://api.github.com/users/YaredBachaGari/received_events",
"type": "User",
"site_admin": false,
"name": "Yared Gari",
"company": 'McKinsey & Company',
"blog": "",
"location": 'Atlanata',
"email": null,
"hireable": null,
"bio": null,
"twitter_username": null,
"public_repos": 46,
"public_gists": 1,
"followers": 14,
"following": 0,
"created_at": "2016-12-29T11:02:06Z",
"updated_at": "2022-05-09T01:43:13Z"
};
